// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartPark.Data;

#nullable disable

namespace SmartPark.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SmartPark.Models.Estacionamento", b =>
                {
                    b.Property<string>("Placa")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("HoraChegada")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HoraSaida")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TipoVeiculo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValorAPagar")
                        .HasColumnType("double");

                    b.HasKey("Placa", "HoraChegada");

                    b.ToTable("Estacionamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
